const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "aarav@ems.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Prepare Monthly Report",
        taskDescription: "Compile data and create the monthly sales report.",
        taskDate: "2025-02-01",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Client Follow-up",
        taskDescription: "Email clients to confirm project requirements.",
        taskDate: "2025-02-03",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Update Website Content",
        taskDescription: "Revise homepage banners and update blog posts.",
        taskDate: "2025-01-28",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      total: 3,
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 2,
    firstName: "Ishaan",
    email: "ishaan@ems.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Design Mockups",
        taskDescription: "Create UI mockups for the new mobile app.",
        taskDate: "2025-02-05",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Team Meeting",
        taskDescription: "Discuss project deadlines with the development team.",
        taskDate: "2025-01-30",
        category: "Management",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Bug Fixes",
        taskDescription: "Resolve bugs reported in the last QA cycle.",
        taskDate: "2025-02-02",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Write Documentation",
        taskDescription: "Draft technical documentation for API endpoints.",
        taskDate: "2025-01-29",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      total: 4,
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
  },
  {
    id: 3,
    firstName: "Vihaan",
    email: "vihaan@ems.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Database Backup",
        taskDescription: "Schedule and verify daily database backups.",
        taskDate: "2025-01-31",
        category: "IT",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Security Audit",
        taskDescription: "Perform security audits for cloud applications.",
        taskDate: "2025-02-06",
        category: "Security",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Server Maintenance",
        taskDescription: "Apply security patches and restart servers.",
        taskDate: "2025-01-27",
        category: "IT",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      total: 3,
      active: 1,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    firstName: "Arjun",
    email: "arjun@ems.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Market Research",
        taskDescription: "Analyze competitor products and market trends.",
        taskDate: "2025-02-04",
        category: "Marketing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Ad Campaign Setup",
        taskDescription: "Configure Google Ads campaigns for Q1.",
        taskDate: "2025-01-29",
        category: "Advertising",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "SEO Optimisation",
        taskDescription: "Improve website SEO rankings with content updates.",
        taskDate: "2025-01-31",
        category: "SEO",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Newsletter Draft",
        taskDescription: "Create draft content for the monthly newsletter.",
        taskDate: "2025-01-28",
        category: "Content",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Product Survey Analysis",
        taskDescription: "Analyze feedback from the latest product survey.",
        taskDate: "2025-02-01",
        category: "Analytics",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      total: 5,
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Kabir",
    email: "kabir@ems.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Employee Training",
        taskDescription: "Organize training sessions for new hires.",
        taskDate: "2025-02-03",
        category: "HR",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Policy Review",
        taskDescription: "Review and update company HR policies.",
        taskDate: "2025-01-30",
        category: "Compliance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Interview Scheduling",
        taskDescription: "Coordinate interview slots for new applicants.",
        taskDate: "2025-01-26",
        category: "Recruitment",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Onboarding Process",
        taskDescription: "Streamline onboarding documents for new employees.",
        taskDate: "2025-02-07",
        category: "HR",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      total: 4,
      active: 2,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
